version: "3"

services:
    db:
        image: postgres
        restart: "always"
        env_file:
            - metabase/config/postgres_exemple.env
        ports:
            - 5432:5432
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./metabase/services/:/docker-entrypoint-initdb.d/
        networks:
            - simple-network
    metabase:
        image: metabase/metabase
        ports:
            - 3000:3000
        depends_on:
            - db
        networks:
            - simple-network
        volumes:
            - metabase_data:/metabase-data
        env_file:
            - metabase/config/metabase_database_exemple.env
    app:
        build:
            context: .
        depends_on:
            - db
        networks:
            - simple-network
networks:
    simple-network:

volumes:
    db_data:
    metabase_data:
