name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
permissions:
    contents: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            uses: actions/checkout@v3
            uses: actions/setup-python@v4
            with:
                python-version: 3.8
            - name: Run Image
            uses: abatilo/actions-poetry@v2.1.6
            with:
                poetry-version: 1.3.2
            - name: Install dependencies
            run: poetry install
            - name: Run tests
            run: poetry run pytest
    code-quality:
        runs-on: ubuntu-latest
        steps:
            uses: actions/checkout@v3
            uses: actions/setup-python@v4
            with:
                python-version: 3.8
            - name: Run Image
            uses: abatilo/actions-poetry@v2.1.6
            with:
                poetry-version: 1.3.2
            - name: Install dependencies
            run: poetry install
            - name: Run black
            run: poetry run black . --check 
            - name: Run bandit
            run: poetry run bandit .
            - name: Run Pylint
            run: poetry run pylint src/
    build-and-deploy-docs:
        runs-on: macos-latest
        steps:
            - name: Requirements
              run: brew install doxygen
                  && brew install sphinx-doc
                  && pip3 install sphinx-rtd-theme
                  && pip3 install breathe
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Build docs
              run: cd docs
                  && make html
                  && cd _build/html
                  && touch .nojekyll
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.4.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: docs/_build/html
