name: Deploy docs

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
permissions:
    contents: write

jobs:
    build-and-deploy:
        runs-on: macos-latest
        steps:
            - name: Requirements
              run: brew install doxygen
                  && brew install sphinx-doc
                  && pip3 install sphinx-rtd-theme
                  && pip3 install breathe
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Build docs
              run: cd docs
                  && make html
                  && cd _build/html
                  && touch .nojekyll
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.4.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: docs/_build/html
