name: Release

on:
    release:
        types:
            - created
permissions:
    contents: write

jobs:
    publish-service-client-package:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Publish PyPi package
              uses: coveooss/pypi-publish-with-poetry@v1.0.0
              with:
                  project-name: Trabalho de GCES
                  PUBLISH_REGISTRY_PASSWORD: ${{ secrets.PYPITOKEN }}
