name: Release

on:
    release:
        types: 
            - created
permissions:
    contents: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: python setup
              uses: actions/setup-python@v4
              with:
                  python-version: 3.8
            - name: Run Image
              uses: abatilo/actions-poetry@v2.1.6
              with:
                  poetry-version: 1.3.2
            - name: Publish
              env:
                  PYPI_USERNAME: ${{ secrets.PYPITOKEN }}
              run: |
          poetry config pypi-token.pypi $PYPITOKEN
          poetry publish --build